module.exports = {
  CONNECTION: 'connection',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_DISCONNECTION: 'disconnection',
  MATCH_PARTNER_UNAVAILABLE: 'MATCH_PARTNER_UNAVAILABLE',
  MATCH_PARTNER_ENTERED: 'MATCH_PARTNER_ENTERED',
  REFUSE_MATCH_INVITATION: 'REFUSE_MATCH_INVITATION',
  ACCEPT_MATCH_INVITATION: 'ACCEPT_MATCH_INVITATION',
  PENDING_MATCH_ACCEPTANCE: 'PENDING_MATCH_ACCEPTANCE',
  SEND_MATCH_INVITATION: 'SEND_MATCH_INVITATION',
  FIND_MATCH_PARTNER: 'FIND_MATCH_PARTNER',
  MATCH_PARTNER_REFUSE_MATCH_INVITATION: 'MATCH_PARTNER_REFUSE_MATCH_INVITATION',
};
