module.exports = {
  CONNECTION: 'connection',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_DISCONNECTION: 'disconnection',
  REFUSE: 'REFUSE',
  JOIN_OPPONENT: 'JOIN_OPPONENT',
  ACCEPTANCE: 'ACCEPTANCE',
  NO_OPPONENT: 'NO_OPPONENT',
  WAITING_TO_ACCEPT: 'WAITING_TO_ACCEPT',
  INVITE: 'INVITE',
  REQUEST_OPPONENT: 'REQUEST_OPPONENT',
};
